class Dua {
  final String arabic;
  final String transliteration;
  final String source;

  /// Translations keyed by locale code (en, es, ur, fr, id, zh, ja, bn, tr,
  /// sw, de, nl, pt, it, fa). No 'ar' entry — Arabic-locale readers are served
  /// directly by [arabic] above, the same convention used in duas_screen.dart.
  final Map<String, String> translations;

  const Dua({
    required this.arabic,
    required this.transliteration,
    required this.source,
    required this.translations,
  });

  String translationFor(String locale) =>
      translations[locale] ?? translations['en']!;
}

const List<Dua> lockScreenDuas = [
  Dua(
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ\nفِي الدُّنْيَا وَالآخِرَةِ',
    transliteration: 'Allahumma inni as\'aluka al-\'afwa wal-\'afiyah\nfid-dunya wal-akhirah',
    source: 'Ibn Majah',
    translations: {
      'en': 'O Allah, I ask You for pardon and well-being\nin this world and the next.',
      'es': 'Oh Allah, te pido perdón y bienestar\nen esta vida y en la otra.',
      'ur': 'اے اللہ! میں تجھ سے دنیا اور آخرت میں\nعفو اور عافیت کا سوال کرتا ہوں۔',
      'fr': 'Ô Allah, je Te demande le pardon et le bien-être\ndans cette vie et dans l\'autre.',
      'id': 'Ya Allah, aku memohon kepada-Mu ampunan dan keselamatan\ndi dunia dan akhirat.',
      'zh': '主啊，求你在今世和后世\n赐予我饶恕与平安。',
      'ja': 'アッラーよ、この世とあの世における\n寛恕と健康をあなたに願います。',
      'bn': 'হে আল্লাহ! আমি তোমার কাছে দুনিয়া ও আখিরাতে\nক্ষমা ও নিরাপত্তা চাই।',
      'tr': 'Allah\'ım! Senden dünyada ve ahirette\nbağışlanma ve afiyet dilerim.',
      'sw': 'Ee Mwenyezi Mungu, nakuomba msamaha na uzima\nkatika dunia hii na ya akhera.',
      'de': 'O Allah, ich bitte Dich um Verzeihung und Wohlergehen\nin dieser Welt und im Jenseits.',
      'nl': 'O Allah, ik vraag U om vergeving en welzijn\nin dit leven en het volgende.',
      'pt': 'Ó Allah, peço-Te perdão e bem-estar\nnesta vida e na próxima.',
      'it': 'O Allah, Ti chiedo perdono e benessere\nin questa vita e nell\'altra.',
      'fa': 'خدایا، از تو گذشت و عافیت را\nدر دنیا و آخرت می‌خواهم.',
    },
  ),
  Dua(
    arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ\nسُبْحَانَ اللَّهِ الْعَظِيمِ',
    transliteration: 'Subhanallahi wa bihamdih\nSubhanallahil-\'Azim',
    source: 'Bukhari & Muslim',
    translations: {
      'en': 'Glory be to Allah and His is the praise.\nGlory be to Allah, the Magnificent.',
      'es': 'Gloria a Allah y Suya es la alabanza.\nGloria a Allah, el Magnífico.',
      'ur': 'اللہ پاک ہے اور اسی کی حمد ہے۔\nاللہ پاک ہے، عظمت والا۔',
      'fr': 'Gloire à Allah et à Lui la louange.\nGloire à Allah, le Magnifique.',
      'id': 'Maha Suci Allah dan segala puji bagi-Nya.\nMaha Suci Allah, Yang Maha Agung.',
      'zh': '真主是清净的，一切赞美归于他。\n真主是清净的，至大的主。',
      'ja': 'アッラーに称えあれ、讃美はアッラーのもの。\nアッラーに称えあれ、至高なる方。',
      'bn': 'আল্লাহ পবিত্র এবং সমস্ত প্রশংসা তাঁরই।\nআল্লাহ পবিত্র, মহিমান্বিত।',
      'tr': 'Allah\'ı tüm noksanlıklardan tenzih ederim, hamd O\'na mahsustur.\nAllah\'ı tenzih ederim, O büyüktür.',
      'sw': 'Utukufu ni wa Mwenyezi Mungu na sifa ni zake.\nUtukufu ni wa Mwenyezi Mungu, Mtukufu.',
      'de': 'Gepriesen sei Allah, und Ihm gebührt das Lob.\nGepriesen sei Allah, der Erhabene.',
      'nl': 'Geprezen zij Allah en aan Hem behoort de lof.\nGeprezen zij Allah, de Verhevene.',
      'pt': 'Glorificado seja Allah e Seu é o louvor.\nGlorificado seja Allah, o Magnífico.',
      'it': 'Gloria ad Allah e a Lui appartiene la lode.\nGloria ad Allah, il Magnifico.',
      'fa': 'پاک و منزه است خدا و ستایش از آن اوست.\nپاک و منزه است خدای بزرگ.',
    },
  ),
  Dua(
    arabic: 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً\nوَفِي الآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',
    transliteration: 'Rabbana atina fid-dunya hasanatan\nwa fil-akhirati hasanatan wa qina \'adhab an-nar',
    source: 'Al-Baqarah 2:201',
    translations: {
      'en': 'Our Lord, give us good in this world and good\nin the next, and protect us from the Fire.',
      'es': 'Señor nuestro, danos lo bueno en esta vida y lo bueno\nen la otra, y protégenos del Fuego.',
      'ur': 'اے ہمارے رب! ہمیں دنیا میں بھلائی دے اور آخرت میں بھی\nبھلائی دے، اور ہمیں آگ کے عذاب سے بچا۔',
      'fr': 'Notre Seigneur, accorde-nous une belle part ici-bas et une belle\npart dans l\'au-delà, et protège-nous du Feu.',
      'id': 'Wahai Tuhan kami, berikanlah kepada kami kebaikan di dunia\ndan kebaikan di akhirat, dan peliharalah kami dari siksa neraka.',
      'zh': '我们的主啊，求你在今世给我们美好，在后世\n给我们美好，求你保护我们免遭火狱的刑罚。',
      'ja': '我らの主よ、この世で善きものを、来世でも\n善きものをわれらに与え、火の刑罰からわれらを守ってください。',
      'bn': 'হে আমাদের প্রতিপালক! আমাদের দুনিয়াতে কল্যাণ দান করো এবং\nআখিরাতেও কল্যাণ দান করো, এবং আমাদেরকে আগুনের শাস্তি থেকে রক্ষা করো।',
      'tr': 'Rabbimiz! Bize dünyada da iyilik ver, ahirette de\niyilik ver. Bizi ateşin azabından koru.',
      'sw': 'Mola wetu Mlezi, tupe wema duniani na wema\nakhera, na utulinde na adhabu ya Moto.',
      'de': 'Unser Herr, gib uns Gutes in dieser Welt und Gutes\nim Jenseits, und bewahre uns vor der Strafe des Feuers.',
      'nl': 'Onze Heer, geef ons het goede in dit leven en het goede\nin het volgende, en bescherm ons tegen de bestraffing van het Vuur.',
      'pt': 'Senhor nosso, dá-nos o bem nesta vida e o bem\nna próxima, e protege-nos do castigo do Fogo.',
      'it': 'Signore nostro, dacci il bene in questa vita e il bene\nnell\'altra, e proteggici dal castigo del Fuoco.',
      'fa': 'پروردگارا، در دنیا به ما نیکی عطا کن و در آخرت\nنیز نیکی، و ما را از عذاب آتش نگاه دار.',
    },
  ),
  Dua(
    arabic: 'حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ\nنِعْمَ الْمَوْلَى وَنِعْمَ النَّصِيرُ',
    transliteration: 'Hasbunallahu wa ni\'mal-wakil\nNi\'mal-mawla wa ni\'man-nasir',
    source: 'Al-Imran 3:173',
    translations: {
      'en': 'Allah is sufficient for us, and He is the best\ndisposer of affairs, the best Protector.',
      'es': 'Allah nos basta, y Él es el mejor\nprotector de los asuntos, el mejor Protector.',
      'ur': 'اللہ ہمیں کافی ہے اور وہ بہترین کارساز ہے،\nبہترین مولیٰ اور بہترین مددگار ہے۔',
      'fr': 'Allah nous suffit, et Il est le meilleur\ngarant, le meilleur Protecteur.',
      'id': 'Allah cukup bagi kami, dan Dialah sebaik-baik\nPelindung, sebaik-baik Penolong.',
      'zh': '真主对我们已足够，他是最好的\n监护者，最好的保护者。',
      'ja': 'アッラーはわれらに十分な方であり、彼こそ\n最善の管理者、最善の守護者です。',
      'bn': 'আল্লাহ আমাদের জন্য পর্যাপ্ত এবং তিনিই উত্তম কর্মবিধায়ক,\nউত্তম মালিক এবং উত্তম সাহায্যকারী।',
      'tr': 'Allah bize yeter, O ne güzel vekildir,\nne güzel dost ve ne güzel yardımcıdır.',
      'sw': 'Mwenyezi Mungu anatutosha, naye ni Mlinzi\nbora, Msaidizi bora.',
      'de': 'Allah genügt uns, und Er ist der beste\nSachwalter, der beste Beschützer.',
      'nl': 'Allah is ons genoeg, en Hij is de beste\nBeheerder, de beste Beschermer.',
      'pt': 'Allah nos basta, e Ele é o melhor\nadministrador, o melhor Protetor.',
      'it': 'Allah ci basta, ed Egli è il miglior\namministratore, il miglior Protettore.',
      'fa': 'خدا ما را بس است و او بهترین\nکارساز و بهترین یاور است.',
    },
  ),
  Dua(
    arabic: 'رَبِّ اشْرَحْ لِي صَدْرِي\nوَيَسِّرْ لِي أَمْرِي',
    transliteration: 'Rabbi ishrah li sadri\nwa yassir li amri',
    source: 'Ta-Ha 20:25–26',
    translations: {
      'en': 'My Lord, expand my breast for me\nand ease my task for me.',
      'es': 'Señor mío, ensancha mi pecho\ny facilítame mi tarea.',
      'ur': 'اے میرے رب! میرا سینہ کھول دے\nاور میرے کام میں آسانی پیدا کر۔',
      'fr': 'Mon Seigneur, élargis ma poitrine\net facilite-moi ma tâche.',
      'id': 'Ya Tuhanku, lapangkanlah dadaku\ndan mudahkanlah urusanku.',
      'zh': '我的主啊，求你扩展我的胸襟，\n求你使我的事情容易。',
      'ja': '我が主よ、わが胸を広げ、\nわが任務を容易にしてください。',
      'bn': 'হে আমার প্রতিপালক! আমার বক্ষ প্রশস্ত করে দাও\nএবং আমার কাজ সহজ করে দাও।',
      'tr': 'Rabbim! Göğsümü aç\nve işimi bana kolaylaştır.',
      'sw': 'Mola wangu Mlezi, nipanulie kifua changu\nna unirahisishie jambo langu.',
      'de': 'Mein Herr, weite meine Brust\nund erleichtere mir meine Aufgabe.',
      'nl': 'Mijn Heer, verruim mijn borst\nen maak mijn taak gemakkelijk voor mij.',
      'pt': 'Senhor meu, expande o meu peito\ne facilita a minha tarefa.',
      'it': 'Signore mio, allarga il mio petto\ne facilita il mio compito.',
      'fa': 'پروردگارا، سینه‌ام را برایم بگشا\nو کارم را برایم آسان گردان.',
    },
  ),
];

const List<Dua> focusDuas = [
  Dua(
    arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ',
    transliteration: 'Subhanallahi wa bihamdih',
    source: 'Bukhari & Muslim',
    translations: {
      'en': 'Glory be to Allah and His is the praise.',
      'es': 'Gloria a Allah y Suya es la alabanza.',
      'ur': 'اللہ پاک ہے اور اسی کی حمد ہے۔',
      'fr': 'Gloire à Allah et à Lui la louange.',
      'id': 'Maha Suci Allah dan segala puji bagi-Nya.',
      'zh': '真主是清净的，一切赞美归于他。',
      'ja': 'アッラーに称えあれ、讃美はアッラーのもの。',
      'bn': 'আল্লাহ পবিত্র এবং সমস্ত প্রশংসা তাঁরই।',
      'tr': 'Allah\'ı tüm noksanlıklardan tenzih ederim, hamd O\'na mahsustur.',
      'sw': 'Utukufu ni wa Mwenyezi Mungu na sifa ni zake.',
      'de': 'Gepriesen sei Allah, und Ihm gebührt das Lob.',
      'nl': 'Geprezen zij Allah en aan Hem behoort de lof.',
      'pt': 'Glorificado seja Allah e Seu é o louvor.',
      'it': 'Gloria ad Allah e a Lui appartiene la lode.',
      'fa': 'پاک و منزه است خدا و ستایش از آن اوست.',
    },
  ),
  Dua(
    arabic: 'اللَّهُ أَكْبَرُ كَبِيرًا\nوَالْحَمْدُ لِلَّهِ كَثِيرًا',
    transliteration: 'Allahu akbaru kabiran\nwal-hamdu lillahi kathiran',
    source: 'Muslim',
    translations: {
      'en': 'Allah is the greatest, the Most Great.\nAll abundant praise belongs to Allah.',
      'es': 'Allah es el más grande, el Sumamente Grande.\nToda alabanza abundante pertenece a Allah.',
      'ur': 'اللہ سب سے بڑا ہے، نہایت بڑا۔\nبہت ساری تعریفیں اللہ ہی کے لیے ہیں۔',
      'fr': 'Allah est le plus grand, le Très Grand.\nToute louange abondante appartient à Allah.',
      'id': 'Allah Maha Besar lagi Sangat Besar.\nSegala puji yang banyak adalah milik Allah.',
      'zh': '真主至大，至为伟大。\n无量的赞美都归于真主。',
      'ja': 'アッラーは至大であり、最も偉大な方。\nあらゆる豊かな讃美はアッラーのもの。',
      'bn': 'আল্লাহ মহান, পরম মহান।\nসকল বিপুল প্রশংসা আল্লাহরই জন্য।',
      'tr': 'Allah en büyüktür, çok büyüktür.\nBol bol hamd Allah\'a mahsustur.',
      'sw': 'Mwenyezi Mungu ni Mkubwa, Mkubwa Zaidi.\nSifa nyingi zote ni za Mwenyezi Mungu.',
      'de': 'Allah ist der Größte, der Allergrößte.\nAller überreiche Lob gebührt Allah.',
      'nl': 'Allah is de Grootste, de Allergrootste.\nAlle overvloedige lof behoort aan Allah.',
      'pt': 'Allah é o maior, o Imenso.\nTodo louvor abundante pertence a Allah.',
      'it': 'Allah è il più grande, il Sommamente Grande.\nOgni abbondante lode appartiene ad Allah.',
      'fa': 'خدا بزرگ‌تر است، بسیار بزرگ.\nو ستایش فراوان از آن خداست.',
    },
  ),
  Dua(
    arabic: 'لَا إِلَهَ إِلَّا اللَّهُ\nوَحْدَهُ لَا شَرِيكَ لَهُ',
    transliteration: 'La ilaha illallahu\nwahdahu la sharika lah',
    source: 'Bukhari & Muslim',
    translations: {
      'en': 'There is no god but Allah,\nalone without any partner.',
      'es': 'No hay más dios que Allah,\núnico, sin asociado alguno.',
      'ur': 'اللہ کے سوا کوئی معبود نہیں،\nوہ یکتا ہے، اس کا کوئی شریک نہیں۔',
      'fr': 'Il n\'y a de divinité qu\'Allah,\nLui seul, sans aucun associé.',
      'id': 'Tidak ada tuhan selain Allah,\nYang Esa, tidak ada sekutu bagi-Nya.',
      'zh': '万物非主，唯有真主，\n独一无二，没有任何伙伴。',
      'ja': 'アッラーの他に神はなく、\n唯一であり、いかなる仲間も持たない。',
      'bn': 'আল্লাহ ব্যতীত কোনো উপাস্য নেই,\nতিনি একক, তাঁর কোনো শরিক নেই।',
      'tr': 'Allah\'tan başka ilah yoktur,\nO tektir, ortağı yoktur.',
      'sw': 'Hapana mola ila Mwenyezi Mungu,\nYeye peke yake, hana mshirika.',
      'de': 'Es gibt keinen Gott außer Allah,\nIhn allein, ohne irgendeinen Partner.',
      'nl': 'Er is geen god dan Allah,\nHem alleen, zonder enige partner.',
      'pt': 'Não há divindade senão Allah,\núnico, sem qualquer parceiro.',
      'it': 'Non c\'è divinità se non Allah,\nLui solo, senza alcun socio.',
      'fa': 'معبودی جز خدا نیست،\nیگانه است و شریکی ندارد.',
    },
  ),
  Dua(
    arabic: 'أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ\nالَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ',
    transliteration: 'Astaghfirullaha al-\'Azim\nalladhi la ilaha illa Huwal-Hayyal-Qayyum',
    source: 'Abu Dawud & Tirmidhi',
    translations: {
      'en': 'I seek forgiveness of Allah the Magnificent,\nbesides Whom none has the right to be worshipped.',
      'es': 'Pido perdón a Allah, el Magnífico,\nfuera de Quien nadie merece ser adorado.',
      'ur': 'میں اللہ عظیم سے بخشش مانگتا ہوں\nجس کے سوا کوئی معبود نہیں۔',
      'fr': 'Je demande pardon à Allah le Magnifique,\nen dehors de qui nul n\'a le droit d\'être adoré.',
      'id': 'Aku memohon ampun kepada Allah Yang Maha Agung,\nyang tidak ada sesembahan yang berhak disembah selain Dia.',
      'zh': '我向至大的真主求恕，\n除他外绝无应受崇拜者。',
      'ja': '至高なるアッラーに赦しを求めます。\n彼の他に崇拝される権利を持つ者はいません。',
      'bn': 'আমি মহান আল্লাহর কাছে ক্ষমা প্রার্থনা করি,\nযিনি ব্যতীত কারো ইবাদত পাওয়ার অধিকার নেই।',
      'tr': 'Kendisinden başka ibadete layık ilah olmayan\nbüyük Allah\'tan bağışlanma dilerim.',
      'sw': 'Namwomba msamaha Mwenyezi Mungu Mtukufu,\nambaye pasipo Yeye hapana yeyote anayestahili kuabudiwa.',
      'de': 'Ich bitte Allah, den Erhabenen, um Verzeihung,\naußer Dem niemand das Recht hat, angebetet zu werden.',
      'nl': 'Ik vraag Allah, de Verhevene, om vergeving,\nnaast Wie niemand het recht heeft aanbeden te worden.',
      'pt': 'Peço perdão a Allah, o Magnífico,\nalém de Quem ninguém tem o direito de ser adorado.',
      'it': 'Chiedo perdono ad Allah, il Magnifico,\noltre il Quale nessuno ha il diritto di essere adorato.',
      'fa': 'از خدای بزرگ آمرزش می‌خواهم،\nکه جز او هیچ معبود برحقی نیست.',
    },
  ),
];
