// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbV4eB7mVOQwj_25anmdxvp23FVAoDcwc',
    appId: '1:141090112561:web:4bde24835b602fe5228110',
    messagingSenderId: '141090112561',
    projectId: 'noor-guard-app-86a13',
    authDomain: 'noor-guard-app-86a13.firebaseapp.com',
    storageBucket: 'noor-guard-app-86a13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaoVZwUhsE45ahOMt4RjVAmKYRMNrJ6sM',
    appId: '1:141090112561:android:1a91772bafb281f4228110',
    messagingSenderId: '141090112561',
    projectId: 'noor-guard-app-86a13',
    storageBucket: 'noor-guard-app-86a13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfIEqznEAl7xpZRoA3r90MWv8qEgHCtGM',
    appId: '1:141090112561:ios:083f5e8581d31d99228110',
    messagingSenderId: '141090112561',
    projectId: 'noor-guard-app-86a13',
    storageBucket: 'noor-guard-app-86a13.firebasestorage.app',
    iosBundleId: 'com.noorguard.app',
  );
}
